### ISSUE TITLE
DefaultBloombergSession doesn't allow customizing SessionOptions

### ISSUE THREAD

**Issue by dm3** [assylias/jBloomberg#10]
Currently `DefaultBloombergSession` holds a static `SessionOptions` object which cannot be customized by the user. I guess that's why the implementation is called 'Default'. However, it seems strange that the only other option a user has is to create (or copy) a whole new implementation of the `BloombergSession` interface in order to set a different server port.

What is the reason behind this and would you accept adding another constructor to `DefaultBloombergSession` with an ability to override the `SessionOptions`?

**Comment by assylias** [comment]
There was no specific reason - pushed a change to allow that. I have not pushed it to Maven Central though so you will need to get the code from github.

**Comment by dm3** [comment]
Thanks for the swift response.
