### ISSUE TITLE
Need a way to check if a session is alive

### ISSUE THREAD

**Issue by dm3** [assylias/jBloomberg#13]
Currently you can only check if a session is live by submitting a request and catching an exception.
It would be nice to be able to have a defined set of states that the session is going through and a way to register a callback on session startup which would get called with the state changes.

We could start with the two main states: `Started` and `Stopped`.

What do you think?

**Comment by assylias** [comment]
There are two states involved:

- the state of the underlying bloomberg session: I don't think there is a way to query its status apart from trying to submit something and see what happens or to track the messages (but I currently don't monitor all the possible session end messages).
- the state of jBloomberg's session, which can be NEW, STARTING, STARTED, STARTUP_FAILED or STOPPED

Giving access to the latter is not a problem - it's essentially about adding a getter.

Giving access to the former is a bit more involved and I'm not sure it can be 100% accurate.

Which one were you thinking of?

**Comment by dm3** [comment]
What I'm writing now is a pool of sessions together with a heartbeat mechanism which does periodic requests, so maybe the right abstraction layer for this is above the `BloombergSession`. 

Would you like to see that in jBloomberg?

**Comment by assylias** [comment]
At first sight yes it looks like it should be a separate class.
I'm happy to include new features from external contributions but if they are material (which seems to be the case) I would need you to sign a CLA. before merging your contribution.
