### ISSUE TITLE
Latest version not in Maven repo

### ISSUE THREAD

**Issue by elgrocho** [assylias/jBloomberg#14]
Hi,

Would it be possible to push the latest version into Maven repo? It looks like some features in source code are not available in 3.3 (custom session options).

Regards,
Lukasz

**Comment by assylias** [comment]
I have pushed v3.4 to Maven Central - it may take a few hours to be available.

**Comment by elgrocho** [comment]
Thank you!

**Comment by assylias** [comment]
No probs - [it's now available].(http://search.maven.org/#artifactdetails%7Ccom.assylias%7Cjbloomberg%7C3.4%7Cjar)
