### ISSUE TITLE
Looking for information

### ISSUE THREAD

**Issue by calmac** [assylias/jBloomberg#20]
Hi Assylias,

Fisrt of all thanks for your work,

I would like to use your library but i don't manage to get an example

My use case get is to get a response matrix (or guava table)  with a list of ticker and a list of bloomberg field

Do you have an example to do this using you library?

Thanks a lot by advance

Kinds regard

oskar

PS: all is ok in my side about setup (bbg.jar and your library)

**Comment by assylias** [comment]
Hi, have you checked the examples at the bottom of [this page](http://assylias.github.io/jBloomberg/apidocs/index.html)?

**Comment by calmac** [comment]
Thanks for your quick answer assylias. It's working. I am familliarizing with you library and it's a great work. If you're interested i can give you a feed back in few days (like use case example or difficulties that i experienced and solved in order to improve your doc ... )

**Comment by assylias** [comment]
Thanks for the kind words @calmac. Yes sure, feel free to share your comments here as feature requests or bug reports.
