### ISSUE TITLE
feature request: ability to retreview 'bsrch' queries.

### ISSUE THREAD

**Issue by jaybert** [assylias/jBloomberg#26]
I started jBloomberg for some bloomberg work and its been great.  The one functionality that I dont think I was able to do was being able to run the bloomberg SRCH data queries.  Here's an example in python on how it is implemented:  It needs to use the ExcelGetGridRequest service functionality via the API unfortunately.

https://github.com/matthewgilbert/pdblp/blob/master/pdblp/pdblp.py

 def bsrch(self, domain):
        """This function uses the Bloomberg API to retrieve 'bsrch'
        (Bloomberg SRCH Data) queries. Returns list of tickers.
        Parameters
        ----------
        domain: string
        A character string with the name of the domain to execute.
        It can be a user defined SRCH screen, commodity screen or
        one of the variety of Bloomberg examples. All domains are in the format
        <domain>:<search_name>. Example "COMDTY:NGFLOW"
        Returns
        -------
        data: pandas.DataFrame
        List of bloomberg tickers from the BSRCH
        """
        logger = _get_logger(self.debug)
        request = self.exrService.createRequest("ExcelGetGridRequest")
        request.set("Domain", domain)
        self.session.sendRequest(request)
        data = []
        # Process received events
        while True:
            event = self.session.nextEvent(self.timeout)
            if event.eventType() == blpapi.Event.RESPONSE or \
               event.eventType() == blpapi.Event.PARTIAL_RESPONSE:
                for msg in event:
                    logger.info(msg)
                    for v in msg.getElement("DataRecords").values():
                        for f in v.getElement("DataFields").values():
                            data.append(f.getElementAsString("StringValue"))
            if event.eventType() == blpapi.Event.RESPONSE:
                break
        return pd.DataFrame(data)

**Comment by assylias** [comment]
Thank you for your message. This feature is not a priority for me at the moment but if you want to implement it and submit a Pull Request I will certainly consider it for inclusion in the project.

**Comment by jaybert** [comment]
Thanks I’ll take a look to see if I can figure it out. I usually don’t do work in java but guessing this shouldn’t be very difficult since I have what should work in python already.   Thanks!

**Comment by jaybert** [comment]
#27 gave it a shot, figured worth getting your view on it before I proceeded any further.  Functionality works / I don't believe there is much in terms of other parameters/overrides that are possible.

**Comment by assylias** [comment]
Fixed with https://github.com/assylias/jBloomberg/commit/70e7a804bd72ec353ffb4be199af1705a39c4a01
