### ISSUE TITLE
blpapi groupId is bloombergblp not bloomberglp

### ISSUE THREAD

**Issue by jonfreedman** [assylias/jBloomberg#28]
Given that Bloomberg's Java package is com.bloomberglp.blpapi is there a reason you have chosen to use com.bloomberg**b**lp as the groupId?

**Comment by assylias** [comment]
Not really no. It was maybe their website address when I started the library 8 years ago.

**Comment by jonfreedman** [comment]
It's just annoying as I am looking at using your library to replace some of the code I've written and I installed their lib with a groupId matching their package name.  I'm going to create some PRs to add some further functionality soon, I'll make sure to not include the change I've made to pom.xml

**Comment by assylias** [comment]
I see - I'll leave it as is for now then. Thank you very much for your interest.
