### ISSUE TITLE
Allow pass through of "useGMT" option when creating a subscription

### ISSUE THREAD

**Issue by jonfreedman** [assylias/jBloomberg#37]
By default timestamps reflect the users preference set in `TZDF`, adding the "useGMT" option forces timestamps to be returned in UTC consistently across users and locations.

**Comment by assylias** [comment]
See https://github.com/assylias/jBloomberg/pull/39#issuecomment-422757339

We return an `OffsetTime` with the wrong offset when the user `TZDF` settings is not UTC.
