### ISSUE TITLE
Issue on date formating (appears few days ago) 

### ISSUE THREAD

**Issue by lemdev** [assylias/jBloomberg#57]
Hi Assylias
First of all, thanks for you work I use your library every day since few years and it was very helpful for my work.
I think Bloomberg made an update on the time zone in the date format and this create a runtime time exception on line 35 of com.assylias.jbloomberg.HistoricalResultParser.
May I suggest you a modification like 
final LocalDate date = parseLocalDate(firstField.getValueAsString().substring(0,10));
instead of 
final LocalDate date = parseLocalDate(firstField.getValueAsString());
If you think it is a bad idea no problem, I have rebuilt your lib with this correction and it’s work for me.
Thanks again for your work
Kinds regards
Alx

**Comment by assylias** [comment]
Hi Alx, thank you for your message.
I thought I fixed the issue with this commit: https://github.com/assylias/jBloomberg/commit/a8a02a91103ba53decda878b759056d90ebdce74

But I can see in your proposal that you are already using that version. Do you mind showing me the format Bloomberg is sending? There may be a way to amend the parser instead of using substring.

**Comment by lemdev** [comment]
Thanks for your quick response. i agree with your solution, she is more elegant, I will try to reproduce the problem in an isolated class (it pop currently on a big program) and send to you

**Comment by lemdev** [comment]
Ok I got it,
The modification is on the commit a8a02a9 (30-March-2022)
And when I write in my pom

dependency
	groupId>com.assylias</groupId
	artifactId>jbloomberg</artifactId
	version>3.7</version
dependency

I get the last version on maven, which is dated of 29-Aug-2018 and doesn't contains the patch a8a02a9.

So in conclusion, if I want the last version I have to download the source code on your github, build it by myself and then make a manual maven installation. I have done this and it works.

If I may and with the most possible respect, I feel it would be easier for your users that you push a compiled version with the patch on maven central repository.

Thanks for your time and your answer

Alx

**Comment by assylias** [comment]
Good to know you got it to work, thanks for testing. I will try to find some time and publish a new version.
